GET {{baseUrl}}/players HTTP/1.1


### Create player
POST http://localhost:4000/api/players HTTP/1.1
content-type: application/json

{
    "name": "Example Player2"
}

### Update player
PUT {{baseUrl}}/players/1 HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "name": "Example Player 2"
}

### Send game
POST {{baseUrl}}/games/1 HTTP/1.1
Authorization: Bearer {{token}}

### Delete player games
DELETE {{baseUrl}}/games/1 HTTP/1.1

### GET player games
GET {{baseUrl}}/games/1 HTTP/1.1

### GET ranking
GET {{baseUrl}}/ranking HTTP/1.1

### GET ranking looser
GET {{baseUrl}}/ranking/loser HTTP/1.1

### GET ranking winner
GET {{baseUrl}}/ranking/winner HTTP/1.1